### ISSUE TITLE
Fails when source code isn't found

### ISSUE THREAD

**Issue by alexmojaki** [friendly-traceback/friendly-traceback#118] opened 2022-02-04 14:08 UTC
It seems your latest changes using stack_data cause a crash when the source code isn't found, e.g:

```python
import friendly_traceback
import traceback
try:
  exec("1/0")
except:
  try:
    friendly_traceback.explain_traceback()
  except:
    traceback.print_exc()
```

Output:

```
Fatal error - aborting
Please report this issue.
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    exec("1/0")
  File "<string>", line 1, in <module>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/core.py", line 373, in __init__
    self.tb_data = TracebackData(etype, value, tb)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/core.py", line 124, in __init__
    self.locate_error()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/core.py", line 272, in locate_error
    node_info = self.records[-1].node_info  # noqa
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/frame_info.py", line 210, in node_info
    return None, (0, len(self.current_line.text)), self.current_line.text
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/frame_info.py", line 236, in current_line
    return only(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    friendly_traceback.explain_traceback()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/__init__.py", line 88, in explain_traceback
    session.explain_traceback(redirect=redirect)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/config.py", line 197, in explain_traceback
    self.exception_hook(etype, value, tb, redirect=redirect)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/config.py", line 226, in exception_hook
    info = self.get_traceback_info(etype, value, tb)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/config.py", line 272, in get_traceback_info
    self.friendly_info.append(core.FriendlyTraceback(etype, value, tb))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/core.py", line 376, in __init__
    debug_helper.handle_internal_error(e)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/debug_helper.py", line 75, in handle_internal_error
    sys.exit()
SystemExit
```

The essential part:

```
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/friendly_traceback/frame_info.py", line 236, in current_line
    return only(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

I'm guessing it breaks trying to find a matching line in an empty list.

Demo link: https://replit.com/@alexmojaki/LimeLegitimateMachinelanguage#main.py

Does the repo have tests for missing source code?

**Comment by aroberge** [comment] 2022-02-04 14:13
I thought it did; I'll check. Actually, I did find that I had to remove a test (circular import) as it was failing when run with all the other tests.

Thanks for the report.

BTW, I'd really welcome your help in figuring out how to do highlight when a node is effectively spread over multiple lines. I see that IPython handles that, but my code does not.

**Comment by alexmojaki** [comment] 2022-02-04 14:30
IPython leaves it to Pygments and `stack_data.style_with_executing_node`:

https://github.com/ipython/ipython/blob/8520f3063ca36655b5febbbd18bf55e59cb2cbb5/IPython/core/ultratb.py#L830

Here's how `stack_data.Formatter` does it without Pygments (when there's no colour):

https://github.com/alexmojaki/stack_data/blob/637e10e59daae92f5f3bafc97aedbb119c6151e7/stack_data/formatting.py#L181-L188

In particular it uses `Line.executing_node_ranges`.

**Comment by aroberge** [comment] 2022-02-04 15:24
Actually, I just checked with an older version and the bug was always there. I **thought** I had tested that before, but obviously did not.

**Comment by aroberge** [comment] 2022-02-04 15:39
This particular case (using `exec`) should be fixed now. I need to add a unit test and probably make it more robust in case someone uses `compile()` followed by `exec()` with a filename that is of the form `<...>` and whose source is not saved.

Would you mind testing the new version on pypi?

**Closed** 2022-02-04 19:01 UTC

**Comment by alexmojaki** [comment] 2022-02-06 15:57
Very nice! Here are my thoughts:

1. The default red background looks great, much better than the yellow in IPython, for which I take the blame. It's also weird that the traceback in IPython isn't syntax highlighted.
2. Note that IPython will show values from pure_eval with `%xmode verbose`
3. Typo in "so as to no overwhelm": *not
4. Regarding highlighting imports, this is just one of many kinds of node that `executing` doesn't highlight, so it's a stretch to say that you're ensuring a node is highlighted. Hopefully 3.11 will allow changing this.
5. Regarding the highlighting of indentation in multiple lines: I don't know if your version is an improvement. I think the ideal would be to only skip the common leading indentation in the same style as `dedent`, so the `12` and `(` are part of a common highlighted block but it still looks nice and contained.

**Comment by aroberge** [comment] 2022-02-06 16:41
Thanks Alex. I wrote a few lines at the top of the blogpost as an update, mentioning %xmode verbose and the possibility of using a different highlighting strategy - which I will try to do soon.  I also fixed the typo you mentioned.

**Comment by aroberge** [comment] 2022-02-06 21:50
Ok, I managed to do the highlight as you suggested (I think), and I do find that it looks the best.

IPython's way (highlighting to the beginning of the line):
![image](https://user-images.githubusercontent.com/629698/152702657-4a2693ef-3b59-4059-9545-ec82022c9652.png)

My previous way of doing the highlight:
![image](https://user-images.githubusercontent.com/629698/152702689-b3b48842-c998-4cad-97d0-c24454335db9.png)

The new way:
![image](https://user-images.githubusercontent.com/629698/152702697-b31e0957-e59d-4ee6-97e2-bd689337b3fc.png)

The way I have done it is to find the minimum indentation of the 2nd and subsequent lines, and use that as the column from which to highlight. This will look "nice" if the code is indented properly;
however, it might not be as good if the code is not indented so as to follow the natural block structure.

**Comment by alexmojaki** [comment] 2022-02-06 21:57
Do you have examples where it doesn't look good?

Either way it'd be great if you could contribute this to stack_data, then IPython and others could use it too.

**Comment by aroberge** [comment] 2022-02-06 23:33
> Do you have examples where it doesn't look good?

No, I don't. I was mostly thinking of cases where the highlighting of the first line started before what would be the code block that followed it ... but I made another version to take care of this.

As for contributing to stack_data, I could have a look, but I don't know if the approach I use would be easily doable.

Given the following lines that need to be highlighted (taken from the previous pictures)
```
def bar():
    return foo(0) + foo(
        12
    ) + foo(2)
```
I first use stack_data in friendly_traceback to produce the following set of lines:
```
    5: def bar():
 -->6:    return foo(0) + foo(
                          ^^^^
    7:        12
              ^^
    8:    ) + foo(2)
          ^
```
while keeping track of the indentation used for each added line containing carets (^).
If there is more than one such line, I look for the minimum indentation, and parse the output
line by line to make the required adjustments so that the carets are aligned vertically,
ignoring the first line which is assumed to remain unchanged.
```
    5: def bar():
 -->6:    return foo(0) + foo(
                          ^^^^
    7:        12
          ^^^^^^
    8:    ) + foo(2)
          ^
```
I probably could implement something like this for stack_data.
However, I do not know how well this approach would work when using pygments with stack_data.

Friendly takes the output from friendly-traceback and highlights the result line by line.
The problem is that the new input (with line numbers included) is not valid Python syntax.

If a line is not highlighted, I use Pygments (via Rich, using its `Syntax` class) to highlight the line.
If a line needs to be highlighted, I do my own tokenization and use the `Text` class from Rich to highlight each token in a style that is roughly similar to what Pygments does.

However, this line by line highlighting can fail spectacularly when encountering multi-line
triple quoted strings.  I prevent problems by first identifying if such strings are present.
If so, I do not bother with tokenization and, other then the line numbers, I consider the
output to be either "code" or "highlighted code".  Here's an example:
![image](https://user-images.githubusercontent.com/629698/152705710-84445f0e-1027-426f-b953-14c5a6073b18.png)

As you can see, the syntax highlighting is not consistent in the different parts - but the red background is treated correctly and a casual reader is likely not going to notice the difference
in the rest of the code.

The whole thing is an inelegant hack, but I consider the final result to be good enough for me, at least for now.

If the `syntax.stylize()` method mentioned in https://github.com/Textualize/rich/issues/1829 is ever implemented, then, perhaps something better could be done.  Given that I take the output from friendly-traceback that contain line numbers, there might still be problems with triple quoted strings yielding line numbers highlighted in green such as on line 7 of the example below, but that would be less problematic.

![image](https://user-images.githubusercontent.com/629698/152705988-312b08fa-cecf-4787-af1d-220eeeff9b00.png)

From what I can see from IPython, it does not do syntax coloring of the output
![image](https://user-images.githubusercontent.com/629698/152706126-bd964181-9fd9-423b-9a9c-af76f5bdfbce.png)

I did that initially, but I liked the full syntax colored version better - when it works!

===
Anyway, I will try to have a look at stack_data (hopefully this week) and see if I can come up with something acceptable.

**Comment by alexmojaki** [comment] 2022-02-07 11:25
> Friendly takes the output from friendly-traceback and highlights the result line by line.

Well there's your problem. IMHO friendly-traceback should be similar to stack_data in that its primary responsibility should be to provide structured information that other code can use effectively however it wants. It can still include helpers for formatting to make things easier for users, but `friendly` should have access to more than a formatted string which it then has to parse and reformat.

> From what I can see from IPython, it does not do syntax coloring of the output

I don't know what's happening in your system, but I can see that it's bolding the keywords `def` and `return`, and in your blog post I can see that Jupyter has syntax highlighting in its tracebacks. Here's a screenshot from IPython in my system:

![Screenshot from 2022-02-07 12-54-06](https://user-images.githubusercontent.com/3627481/152774931-cb9ebc65-911b-492d-83d9-a22683025015.png)

Here's how that happens:

1. `IPython.core.ultratb._format_traceback_lines` calls `stack_line.render(pygmented=has_colors)` for each line, then adds its own line numbers, arrows etc. around that.
2. `stack_data.core.Line.render` calls `self.frame_info._pygmented_scope_lines` which returns a list of cached strings representing rendered lines, and picks the correct one.
3. `stack_data.core.FrameInfo._pygmented_scope_lines` constructs the appropriate ranges based on `executing` and passes them to `_pygmented_with_ranges(formatter, code, ranges)`, from which it extracts the relevant lines.
4. `stack_data.utils._pygmented_with_ranges` calls `pygments.highlight(code, lexer, formatter).splitlines()`. So `pygments` receives a full syntactically valid code block and it can deal with multiline strings properly, but `IPython` can still work with individual lines.

**Comment by aroberge** [comment] 2022-02-07 18:32
>> Friendly takes the output from friendly-traceback and highlights the result line by line.

> Well there's your problem. IMHO friendly-traceback should be similar to stack_data in that its primary responsibility should be to provide structured information that other code can use effectively however it wants. It can still include helpers for formatting to make things easier for users, but friendly should have access to more than a formatted string which it then has to parse and reformat.

I completely agree; I should have thought of this before, when I first struggled to "unparse" the information given by friendly_traceback so that it could be properly shown by friendly within IDLE.

I need to have friendly_traceback provide its own formatted output **and** to also provide the raw information in a structure way (code, line_numbers including the one to flag as containing the error, location/range of markers) so that other programs can make use of it in their own way. This is what I already do for all the other information provided by friendly_traceback, which you know since you already use some of them selectively for futurecoder.  

This will likely mean that I'll have to reimplement my own version of what Rich currently does for me "out of the box".  Since I already use stack_data, perhaps I can bypass Rich for this part of the information provided by friendly.

Also, thanks for the added explanation of the logical steps followed for IPython formatting. This will  be a useful guide when reading the code, and seeing how much information I can reuse from stack_data.

However, my next order of business will be to see if I can modify stack_data to highlight multiple lines following your suggestion. If I can do this (perhaps later today if I can do enough of my paid work first), I'll submit a pull request so that you can decide if it is worthwhile or not.
