### ISSUE TITLE
Identify missing import

### ISSUE THREAD

**Issue by JulienPalard** [friendly-traceback/friendly-traceback#76] opened 2021-11-12 07:53 UTC
In the following case:

```pytb
Traceback (most recent call last):
  File "solution.py", line 1, in <module>
    p = Path("words.txt")
NameError: name 'Path' is not defined
```

it would be great if a message like: 

> You're missing a `from pathlib import Path` import.

I don't know if there exist clean ways to do it, but auto-generating a dict from all `__all__`s (~once for all) and using it should work.

**Comment by aroberge** [comment] 2021-11-12 11:30
In the past, I had thought of doing something like this for a few "common" modules, inspired by Thonny does something like this for a few modules, including `turtle`. The standard library contains over 200 hundred different modules, with possible some changes depending on which Python version is used. In some cases, including NameError, AttributeError, and ModuleNotFoundError, I do refer to a list of these modules [1] to see if the error might be caused by a typo in the module name.  This does catch "by accident" a missing import for the turtle module in the following example:
```
[3]: t = Turtle()

Traceback (most recent call last):
  Code block [3], line 1, in <module>
    t = Turtle()
NameError: name 'Turtle' is not defined

        Did you forget to import `turtle`?

[4]: why()

    The name `Turtle` is not defined in your program.
    Perhaps you forgot to import `turtle` which is found
    in Python's standard library.
    Note that the name of the module is `turtle` and not `Turtle`.
```

I will look into doing this for all names listed in [1]. This might leave out some names available from subpackages (such as os.path) but it would be an improvement.

[1] https://github.com/friendly-traceback/friendly-traceback/blob/main/friendly_traceback/runtime_errors/stdlib_modules.py

**Comment by aroberge** [comment] 2021-11-21 12:47
New version:
```
Friendly-traceback version 0.4.80. [Python version: 3.8.4]
Type 'Friendly' for help on special functions/methods.

[1]: set_include('why')

[2]: p = Path('words.txt')

    In your program, no object with the name `Path` exists.
    `Path` is a name found in the following modules from the standard library:
    compileall, pathlib, zipfile.
    Perhaps you forgot to import `Path` from one of these modules.


[3]: import pathlib

[4]: p = Path('words.txt')

    In your program, no object with the name `Path` exists.
    The similar name `pathlib` was found in the local scope.

    The local object `pathlib`
    has an attribute named `Path`.
    Perhaps you should have written `pathlib.Path`
    instead of `Path`.


[5]: BEVEL

    In your program, no object with the name `BEVEL` exists.
    `BEVEL` is a name found in module `tkinter`.
    Perhaps you forgot to write

        from tkinter import BEVEL.
```
I will close this issue after I commit some unit tests.

**Closed** 2021-11-21 13:12 UTC

**Comment by aroberge** [comment] 2021-11-21 21:39
Note: the newest version does a better job in identifying similar words and no longer suggest that 'pathlib' is similar to 'Path'.
