### ISSUE TITLE
Custom showwarning fails when source isn't available

### ISSUE THREAD

**Issue by alexmojaki** [friendly-traceback/friendly-traceback#185] opened 2022-10-02 13:05 UTC
1. I run tests locally with Python 3.8
2. It tries to show a warning about something
3. `about_warnings.show_warning` is used
4. It calls `inspect.getouterframes`
5. which calls `inspect.findsource`
6. which fails on the filename `<frozen importlib._bootstrap>` because it has no source code

Here's a more direct repro:

```python
from friendly_traceback import about_warnings

about_warnings.enable_warnings()

exec("""
import warnings

warnings.warn("This is a warning")
""")
```

which shows

```pytb
Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2022.2/scratches/scratch_2291.py", line 5, in <module>
    exec("""
  File "<string>", line 4, in <module>
  File "/home/alex/.pyenv/versions/3.8.5/lib/python3.8/warnings.py", line 109, in _showwarnmsg
    sw(msg.message, msg.category, msg.filename, msg.lineno,
  File "/home/alex/work/friendly-traceback/friendly_traceback/about_warnings.py", line 167, in show_warning
    for outer_frame in inspect.getouterframes(inspect.currentframe()):
  File "/home/alex/.pyenv/versions/3.8.5/lib/python3.8/inspect.py", line 1491, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/home/alex/.pyenv/versions/3.8.5/lib/python3.8/inspect.py", line 1465, in getframeinfo
    lines, lnum = findsource(frame)
  File "/home/alex/.pyenv/versions/3.8.5/lib/python3.8/inspect.py", line 840, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range
```

**Comment by aroberge** [comment] 2022-10-02 13:24
How are you running it?  I cannot reproduce it.
```
> python ignore4.py
`UserWarning`: This is a warning

(venv-friendly-traceback-3.8) C:\Users\Andre\github\friendly-traceback
> python -m friendly_traceback ignore4.py
`UserWarning`: This is a warning

(venv-friendly-traceback-3.8) C:\Users\Andre\github\friendly-traceback
> type ignore4.py
from friendly_traceback import about_warnings
about_warnings.enable_warnings()

exec("""
import warnings

warnings.warn("This is a warning")
""")
```

**Comment by aroberge** [comment] 2022-10-02 13:25
I am using Python 3.8.10; perhaps this causes the different behaviour.

**Comment by aroberge** [comment] 2022-10-02 13:26
Ok, I can reproduce it with 3.7.9

```
(venv-friendly-traceback-3.7) C:\Users\Andre\github\friendly-traceback
> python ignore4.py
Traceback (most recent call last):
  File "ignore4.py", line 8, in <module>
    """)
  File "<string>", line 4, in <module>
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python37\lib\warnings.py", line 110, in _showwarnmsg
    msg.file, msg.line)
  File "C:\Users\Andre\github\friendly-traceback\friendly_traceback\about_warnings.py", line 167, in show_warning
    for outer_frame in inspect.getouterframes(inspect.currentframe()):
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python37\lib\inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python37\lib\inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python37\lib\inspect.py", line 828, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range
```

**Comment by aroberge** [comment] 2022-10-02 13:36
Ok, fixed with new version about to be uploaded to Pypi.
```
(venv-friendly-traceback-3.7) C:\Users\Andre\github\friendly-traceback
> python ignore4.py
`UserWarning`: This is a warning
```
And, if using with friendly_traceback

```
> python -m friendly_traceback ignore4.py
`UserWarning`: This is a warning

(venv-friendly-traceback-3.7) C:\Users\Andre\github\friendly-traceback
> python -im friendly_traceback ignore4.py
`UserWarning`: This is a warning

Friendly-traceback version 0.7.30. [Python version: 3.7.9]
Type 'Friendly' for help on special functions/methods.

[1]: history()
0. UserWarning: This is a warning

[2]: explain()

    UserWarning: This is a warning

    `UserWarning` is the default class for `warnings.warn()`.

    Warning issued on line `4` of file 'HOME:\github\friendly-traceback\ignore4.py'.

<'source unavailable'>
```

**Comment by aroberge** [comment] 2022-10-02 13:39
And, of course, the following is nicer! ;-)

```
from friendly_traceback import about_warnings, friendly_exec
about_warnings.enable_warnings()

friendly_exec("""
import warnings

warnings.warn("This is a warning")
""")
```

Running it:
```
> python -im friendly_traceback ignore4.py
`UserWarning`: This is a warning

Friendly-traceback version 0.7.30. [Python version: 3.9.10]
Type 'Friendly' for help on special functions/methods.

[1]: history()
0. UserWarning: This is a warning

[2]: explain()

    UserWarning: This is a warning

    `UserWarning` is the default class for `warnings.warn()`.

    Warning issued on line `4` of file '<friendly-exec-0>'.

       2| import warnings
       3|
    -->4| warnings.warn("This is a warning")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

            warnings:  <module warnings> from PYTHON_LIB:\warnings.py
            warnings.warn:  <builtin function warn>
```

**Comment by aroberge** [comment] 2022-10-02 13:46
I will change the following:
```
- formatted_source = _("<'source unavailable'>")
+ formatted_source = _("The source is unavailable.\n"
                       "If you used `exec`, consider using `friendly_exec` instead.")
```

**Comment by alexmojaki** [comment] 2022-10-02 14:28
Thanks, that worked for me. I'm using 3.8.5.

**Closed** 2022-10-02 14:57 UTC
